# frozen_string_literal: true

# rubocop:disable Layout/LineLength

# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

dates = ['Monday, August 30th 2021 8:00pm', 'Thursday, August 26th 2021 6:00pm', 'Monday, August 29th 2021 8:00pm', 'Wednesday, September 1st 2021 6:00pm']

Workshop.create(title: 'SALTED BAKED FISH', description: "There are few things more impressive than preparing a whole fish, but crust that fish in salt and crack it open at the dinner table - and you've got serious wow factor.
Level up your entertaining with this fabulous class.  The actual technique of baking in salt crust has a murky history with many theories as to where it started, but China, Greece, Italy and Turkey are all important in its roots. Salt baking creates an insulation that allows the fish to gently steam in its own juices which results in a perfectly flavourful and seasoned fish.  Your chef will teach you the method to final presentation, alongside a beautiful Seasonal Mediterranean Salad and Coffee Halva for dessert.
Bring Turkey into your kitchen - it will be a night to remember!", menu: ['Whole Salt Crusted Baked Fish', 'Seasonal Mediterranean Salad with Fresh Fruit', 'Coffee Halva  |  Coffee flavoured Olive Oil dessert'], dates: dates, image: 'https://static.wixstatic.com/media/3106e5_62bf426288004a5db091305c414d421c~mv2.jpg/v1/fill/w_980,h_468,al_c,q_85,usm_0.66_1.00_0.01/3106e5_62bf426288004a5db091305c414d421c~mv2.webp')

Workshop.create(title: 'CHICKEN CACCIATORA', description: "Close your eyes and let's transport to the rolling hills of Tuscany. Directly translating to 'Hunters Chicken' -  this one-pot meal was used to keep hunters full with a hearty stew that could be cooked outdoors over an open fire.  Now, this class is an ode to the family meal.
Your home will fill with the cozy scents of bubbling tomatoes, olives, and spices simmering away on the stove.  While it cooks, you and your chef, video calling you from Italy, will whip up a bechamel for your Fennel Gratin, and then move on to your delicate chocolate, fruit and nut cookies.  This cooking class is one you can't miss. ", menu: ['Pollo alla Cacciatora | Chicken Cacciatora, a whole chicken simmered with tomatoes, olives, wine and tomatoes ', 'Finocchi Gratinati | Fennel baked in a creamy bechamel sauce', 'Biscotti alla Florentini | Traditional Florentine cookies made with chocolate, dried fruit and nuts'], dates: dates, image: 'https://static.wixstatic.com/media/3106e5_61143fdc368c40b6b6b87e46ba8ff724~mv2.jpg/v1/fill/w_980,h_492,al_c,q_85,usm_0.66_1.00_0.01/3106e5_61143fdc368c40b6b6b87e46ba8ff724~mv2.webp')

Workshop.create(title: 'CEVICHE',
                description: "Peru has become a culinary hotspot, but this ancient country is not new at all.  This class pays homage to one of their most important culinary contributions - ceviche.  Master this impressive party dish with a chef video calling you from where it was invented, Peru! Together, you'll make three beautiful hishes that will impress any guest.", menu: ['Nikkei Ceviche | Traditional Peruvian Citrus Cooked Salmon or Tuna', 'Mushroom Ceviche | Citrus Marianded Mushrooms ', 'Causa | Layered Potatoes filled with Avocado and Tuna'], dates: dates, image: 'https://static.wixstatic.com/media/3106e5_ca6007f12fcb49b5886ddcd2cb019d60~mv2.jpg/v1/fill/w_980,h_419,al_c,q_85,usm_0.66_1.00_0.01/3106e5_ca6007f12fcb49b5886ddcd2cb019d60~mv2.webp')

Workshop.create(title: 'ENCHILADAS MINERAS', description: "It’s hard to imagine a mix of such simple ingredients could come together to create such an incredibly mouthwatering meal and yet that's exactly what you’ll do in this class. First, you'll learn how to make Adobo sauce. This sauce plays a key role in your class.  You'll finish with traditional Mexican enchiladas filled with fragrent chicken, and topped with a traditional potato, carrot and cheese garnish. The incredible scents in this Mexican cooking class will bring everyone in the house running.
Learn to create these authentic enchiladas from the town of Guanajuato, a mining town in the middle of Mexico, where women prepared this dish to bring to their husbands at the end of a work day at the mines.
Transport your kitchen to the heart of Mexico.", menu: ['Enchiladas Mineras de Pollo | Hearty Enchiladas filled with chicken and topped with traditional garnishes', 'Adobo sauce | Learn to make Adobe sauce from scratch, this will be used as the sauce for your Enchiladas', 'Guacamole | Authentic, fresh guacamole for dipping'], dates: dates, image: 'https://static.wixstatic.com/media/3106e5_4ff9fa7d7ccd4542aad7d41f943c6ec6~mv2.jpg/v1/fill/w_980,h_470,al_c,q_85,usm_0.66_1.00_0.01/3106e5_4ff9fa7d7ccd4542aad7d41f943c6ec6~mv2.webp')

Workshop.create(title: 'CHICKEN WITH HOLY BASIL & COCONUT SOUP', description: 'Get ready to be whisked away to the streets of Thailand where you can find some of the best food in the world! Chicken with Holy Basil (Pad Kra Phao) is an absolute favourite that has gone well beyond its humble beginnings and can easily be debated as one of the best Thai street dishes of all time! Glazed in a deliciously sweet yet salty sauce, each bite of this chicken dish will be an explosion of flavour. Topped with a fried egg and served with a side of Thai rice, it is perfect for any day of the week.
Round out this meal with a big bowl of fragrant and rich Coconut Soup (Tom Kha Gai), another Thai classic. It will warm your soul. Your meal isn’t complete until you have a sweet Thai dessert, in this case, Sweet Potatoes in Coconut Milk. Incredibly versatile and full of amazing flavour, this entire meal is easy and quick to make.
Transport your kitchen and awaken your senses with the aromatic cuisine of Thailand.', menu: ['Tom Kha Gai | Coconut Chicken Soup', 'Pad Kra Phao | Stir-fried Minced Chicken or Tofu with Holy Thai basil', 'Sweet Potatoes in Coconut Milk with Thai Rice'], dates: dates, image: 'https://static.wixstatic.com/media/2259ce_33431f46493b4c63bbde0c1c04db7edf~mv2.jpg/v1/fill/w_980,h_582,al_c,q_85,usm_0.66_1.00_0.01/2259ce_33431f46493b4c63bbde0c1c04db7edf~mv2.webp')

Workshop.create(title: 'GNOCCHI TWO-WAYS', description: 'Is it Thursday in Italy? Then bring on the gnocchi! Across the country, every Thursday restaurants serve up delicious plates of gnocchi for their special of the evening. But regardless of what night of the week it is, gnocchi makes a wonderful, comforting meal. Pillowy potato dumplings, lightly coated in a beautiful sauce…
While dumplings are not exclusive to Italy, this version is believed to come from Northern Italy where the colder climate is better for growing potatoes vs grains. It was the perfect peasant food, hearty and filling, but inexpensive. These dumplings are also considered a pasta and come in many variations, even as you make your way across Italy you’ll find every region has their own unique version.
In this class let Chef Carlotta and our team of chefs in Italy teach you how to make two classic gnocchi - from scratch! - one in a creamy Gorgonzola sauce and another in a classic, tomato sauce (Gnocchi alla Sorrentina) baked to perfection. And once you know how, you’ll be able to experiment with different ways to dress them up depending on what you’re craving. Let’s head to Italy together and make it Thursday Gnocchi Night!', menu: ['Potato Gnocchi with Gorgonzola Cheese Sauce', 'Gnocchi alla Sorrentina | Baked Gnocchi with a rich Pomodoro Sauce', 'Crispy Radicchio & Aceto Balsamico Vinagrette'], dates: dates, image: 'https://static.wixstatic.com/media/2259ce_7714b2eb85764e7ea156d5995430bc84~mv2.jpeg/v1/fill/w_980,h_492,al_c,q_85,usm_0.66_1.00_0.01/2259ce_7714b2eb85764e7ea156d5995430bc84~mv2.webp')

Workshop.create(title: 'CHICKEN PAELLA', description: "Spain's national dish is not only delicious, it's absolutely stunning, as well. What was traditionally a peasant dish, is now a star on Spanish menus around the world. This Spanish cooking class class will teach you to master Chicken Paella at home.
Our chefs in Spain will guide you step-by-step, live from their homes in Spain, how to make chicken stock, which will be used in your Chicken Paella, along with a traditional Spanish started, Pisto Manchego - similar to  ratatouille.  Once your class is over, you'll disconnect and have a beautiful meal - all without leaving home. ", menu: ['Chicken Paella | Spanish Style Rice with Chicken and Beans', 'Chicken Stock', 'Pisto Manchego  | Cooked Tomato and Pepper Vegetable Ratatouille'], dates: dates, image: 'https://static.wixstatic.com/media/0b0678_5215516683064e479586e4da840ac1e6~mv2.jpg/v1/fill/w_980,h_446,al_c,q_85,usm_0.66_1.00_0.01/0b0678_5215516683064e479586e4da840ac1e6~mv2.webp')

Workshop.create(title: 'LOMO SALTADO', description: "Considered one of Peru's most loved dishes, Lomo Saltado, is considered a 'must have' when travelling to Peru.  In this class you'll learn about the fascinating history of Peru and China, and their culinary combination, known as 'Chifa'. Chifa is a cooking practice that uses the abundance of Peruvian ingredients with Chinese influence, and a tradition that dates back to the 1920's.  This important storyline of your class will be understood best as you taste your final dish.
In this cooking class you will make three different dishes, Lomo Saltado, a traditional beef stirfry, alongside Tacu Tacu and Sarsa Criolla. It's a menu that will elevate your average night-in to a Peruvian fine dining experience.", menu: ['Lomo Saltado | Peruvian "Chifa" Style Beef and Pepper Stirfry', 'Tacu Tacu "a lo pobre" | Rice and Beans with Fried Egg and Plantain', 'Sarsa Criolla | Fresh Onion Side'], dates: dates, image: 'https://static.wixstatic.com/media/3106e5_eb87c28c4d834b1eae6937dd071cc32f~mv2.jpg/v1/fill/w_980,h_468,al_c,q_85,usm_0.66_1.00_0.01/3106e5_eb87c28c4d834b1eae6937dd071cc32f~mv2.webp')

# rubocop:enable Layout/LineLength
